-d C:\Users\Gebruiker\Documents\Trafik_Kontrol\impl\gwsynthesis\Trafik_Kontrol.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst C:\Users\Gebruiker\Documents\Trafik_Kontrol\src\Trafik_Kontrol.cst
-cfg C:\Users\Gebruiker\Documents\Trafik_Kontrol\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 10
